### ISSUE TITLE
Segmentation of the long axis slices. 

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/strainmap#87]
These represent a challenge for the current segmentation routine, not only because of the reduced contrast (especially near the apex), the missing wall at one end (replaced by the valve) and the lack of circular symmetry that can be used as reference for the segments. Implementing a robust segmentation pipeline for these images might require revisiting the design of our current segmenters, - potentially implementing new ones -, the constrains and the definition of the initial shape of the segments. None of these changes, if any, should hinder the performance of the existing segmentation of short axis slices.

- [ ] #88 Implement backend for multiple types of segmentations
- [ ] #89 Implement specific conditions
- [ ] #90 Review strain and velocities view
